allowBuilds:
  "@swc/core": true
  better-sqlite3: true
  ffmpeg-static: true
  protobufjs: true
  puppeteer: true

ignoredBuiltDependencies:
  - puppeteer

minimumReleaseAgeExclude:
  - "@puppeteer/browsers"
  - "@swc/core"
  - "@swc/core-darwin-arm64"
  - "@swc/core-darwin-x64"
  - "@swc/core-linux-arm-gnueabihf"
  - "@swc/core-linux-arm64-gnu"
  - "@swc/core-linux-arm64-musl"
  - "@swc/core-linux-ppc64-gnu"
  - "@swc/core-linux-s390x-gnu"
  - "@swc/core-linux-x64-gnu"
  - "@swc/core-linux-x64-musl"
  - "@swc/core-win32-arm64-msvc"
  - "@swc/core-win32-ia32-msvc"
  - "@swc/core-win32-x64-msvc"
  - "puppeteer"
  - "puppeteer-core"
  - "@emnapi/core"
  - "@emnapi/runtime"
  - better-sqlite3

onlyBuiltDependencies:
  - "@swc/core"
  - better-sqlite3
  - ffmpeg-static
  - protobufjs
  - unrs-resolver
