allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  ffmpeg-static: true
  protobufjs: true
  puppeteer: true

ignoredBuiltDependencies:
  - puppeteer

minimumReleaseAgeExclude:
  - "@emnapi/core@1.11.1"
  - "@emnapi/runtime@1.11.1"
  - better-sqlite3@12.10.1

onlyBuiltDependencies:
  - "@swc/core"
  - better-sqlite3
  - ffmpeg-static
  - protobufjs
  - unrs-resolver
