name: Pages Deployment

on:
    push:
        branches: [pages]

jobs:
    pages:
        name: Pages Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

            - name: Install pnpm
              uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
              with:
                  version: 9

            - name: Install Node.js
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version-file: ".node-version"
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build site
              run: pnpm run build

            - name: Deploy site
              uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
              with:
                  branch: gh-pages
                  folder: out
