name: Build and Push Docker Image to the Container Image Registry

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"

jobs:
  docker:
    uses: stegripe/workflows/.github/workflows/docker-build-and-push.yaml@c6ec6f464e4ff5c49573692e046d7e4185f01d72 # main
    secrets: inherit
