name: Docker Build

on:
  release:
    types:
      - created
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile

jobs:
  docker:
    uses: stegripe/workflows/.github/workflows/docker-build-and-push.yaml@356dbc21510fc935c351c19efa7a8545fe276c41 # main
    secrets: inherit
