name: Build and Push Docker Image to the Container Image Registry

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"

jobs:
  docker:
    uses: stegripe/workflows/.github/workflows/docker-build-and-push.yaml@a779ff9f1fd861c2f4426d090ef3c98ec3bf3426 # main
    secrets: inherit
