name: Lint Code and Compile

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    uses: stegripe/workflows/.github/workflows/pnpm-lint-and-test.yaml@c6ec6f464e4ff5c49573692e046d7e4185f01d72 # main
    secrets: inherit
