name: Lint code and compile setup script

on:
  push:
    branches:
      - pages
  pull_request:
    branches:
      - "**"

jobs:
  test:
    uses: stegripe/workflows/.github/workflows/pnpm-lint-and-test.yaml@564a369e6527436f62073f0f1a0ea6626596c6a9 # main
    secrets: inherit
